Draft_Move


    import FreeCAD as App
    import Draft

    doc = App.newDocument()

    polygon1 = Draft.make_polygon(5, radius=1000)
    polygon2 = Draft.make_polygon(3, radius=500)
    polygon3 = Draft.make_polygon(6, radius=220)

    Draft.move(polygon1, App.Vector(500, 500, 0))
    Draft.move(polygon1, App.Vector(500, 500, 0))
    Draft.move(polygon2, App.Vector(1000, -1000, 0))
    Draft.move(polygon3, App.Vector(-500, -500, 0))

    list1 = [polygon1, polygon2, polygon3]

    vector = App.Vector(-2000, -2000, 0)
    list2 = Draft.move(list1, vector, copy=True)
    list3 = Draft.move(list1, -2*vector, copy=True)

    doc.recompute()


Draft_Rotate

    import FreeCAD as App
    import Draft

    doc = App.newDocument()

    polygon1 = Draft.make_polygon(3, radius=300)
    Draft.move(polygon1, App.Vector(1000, 0, 0))

    # Rotation around the origin
    angle1 = 45
    rot2 = Draft.rotate(polygon1, angle1, copy=True)
    rot3 = Draft.rotate(polygon1, 2*angle1, copy=True)
    rot4 = Draft.rotate(polygon1, 4*angle1, copy=True)

    polygon2 = Draft.make_polygon(3, radius=1000)
    polygon3 = Draft.make_polygon(5, radius=500)
    Draft.move(polygon2, App.Vector(2000, 0, 0))
    Draft.move(polygon3, App.Vector(2000, 0, 0))

    # Rotation around another point
    angle2 = 60
    cen = App.Vector(3100, 0, 0)
    list2 = [polygon2, polygon3]
    rot_list2 = Draft.rotate(list2, angle2, center=cen, copy=True)
    rot_list3 = Draft.rotate(list2, 2*angle2, center=cen, copy=True)
    rot_list4 = Draft.rotate(list2, 4*angle2, center=cen, copy=True)

    doc.recompute()


Draft_Scale

    import FreeCAD as App
    import Draft

    doc = App.newDocument()

    pts = [App.Vector(0, 0, 0), App.Vector(500, 500, 0), App.Vector(600, 0, 0)]
    wire1 = Draft.make_wire(pts, closed=True)
    doc.recompute()

    scale1 = App.Vector(2.3, 0.75, 0)
    wire2 = Draft.scale(wire1, scale1, copy=True)
    doc.recompute()

    scale2 = App.Vector(-2, -1.5, 0)
    wires = Draft.scale([wire1, wire2], scale2, copy=True)
    doc.recompute()



Draft_Mirror

    import FreeCAD as App
    import Draft

    doc = App.newDocument()

    place = App.Placement(FreeCAD.Vector(1000, 0, 0), App.Rotation())
    polygon1 = Draft.make_polygon(3, 750)
    polygon2 = Draft.make_polygon(5, 750, placement=place)

    p1 = App.Vector(2000, -1000, 0)
    p2 = App.Vector(2000, 1000, 0)

    line1 = Draft.make_line(p1, p2)
    mirrored1 = Draft.mirror(polygon1, p1, p2)

    Line2 = Draft.make_line(-p1, -p2)
    mirrored2 = Draft.mirror([polygon1, polygon2], -p1, -p2)

    doc.recompute()


Draft_Offset

    import FreeCAD as App
    import Draft

    doc = App.newDocument()

    p1 = App.Vector(0, 0, 0)
    p2 = App.Vector(1500, 2000, 0)
    p3 = App.Vector(4000, 0, 0)

    wire = Draft.make_wire([p1, p2, p3])
    doc.recompute()

    vector = App.Vector(-200, 150, 0)
    offset1 = Draft.offset(wire, vector, copy=True, bind=True, sym=True)
    offset2 = Draft.offset(wire, 3*vector, copy=True)
    offset3 = Draft.offset(wire, 6*vector, copy=True)
    offset4 = Draft.offset(wire, 9*vector, copy=True)
    offset5 = Draft.offset(wire, 1.5*vector, copy=True, occ=True)

    doc.recompute()


Draft_Trimex

    import FreeCAD as App
    import Draft

    doc = App.newDocument()

    rectangle = Draft.make_rectangle(1500, 500)
    doc.recompute()

    vector = App.Vector(0, 0, 300)
    solid = Draft.extrude(rectangle, vector, solid=True)
    doc.recompute()



Draft_Clone

    import FreeCAD as App
    import Draft

    doc = App.newDocument()

    place = App.Placement(App.Vector(1000, 0, 0), App.Rotation())
    polygon1 = Draft.make_polygon(3, 750)
    polygon2 = Draft.make_polygon(5, 750, placement=place)

    vector = App.Vector(2600, 500, 0)
    cloned_object = Draft.clone([polygon1, polygon2], delta=vector)

    cloned_object.Fuse = True

    doc.recompute()


Draft_OrthoArray

    import FreeCAD as App
    import Draft

    doc = App.newDocument()

    rect = Draft.make_rectangle(1500, 500)
    v_x = App.Vector(1600, 0, 0)
    v_y = App.Vector(0, 600, 0)

    array = Draft.make_ortho_array2d(rect, v_x, v_y, 3, 4)
    doc.recompute()

    import FreeCAD as App
    import Draft

    doc = App.newDocument()

    rect = Draft.make_rectangle(1500, 500)
    v_x = App.Vector(1600, 0, 0)
    v_y = App.Vector(0, 600, 0)

    Draft.array(rect, v_x, v_y, 3, 4)
    doc.recompute()


Draft_PolarArray

    import FreeCAD as App
    import Draft

    doc = App.newDocument()

    tri = Draft.make_polygon(3, 600)
    center = App.Vector(-1600, 0, 0)

    array = Draft.make_polar_array(tri, 8, 270, center)
    doc.recompute()


    import FreeCAD as App
    import Draft

    doc = App.newDocument()

    tri = Draft.make_polygon(3, 600)
    center = App.Vector(-1600, 0, 0)

    Draft.array(tri, center, 270, 8)
    doc.recompute()


Draft_CircularArray

    import FreeCAD as App
    import Draft

    doc = App.newDocument()

    tri = Draft.make_polygon(3, 600)

    array = Draft.make_circular_array(tri, 1800, 1200, 4, 1)
    doc.recompute()


Draft_PathArray

    import FreeCAD as App
    import Draft

    doc = App.newDocument()

    p1 = App.Vector(500, -1000, 0)
    p2 = App.Vector(1500, 1000, 0)
    p3 = App.Vector(3000, 500, 0)
    p4 = App.Vector(4500, 100, 0)
    spline = Draft.make_bspline([p1, p2, p3, p4])
    obj = Draft.make_polygon(3, 500)

    path_array = Draft.make_path_array(obj, spline, 6)
    doc.recompute()

    wire = Draft.make_wire([p1, -p2, -p3, -p4])
    path_array2 = Draft.make_path_array(obj, wire, count=3, extra=App.Vector(0, -500, 0), subelements=["Edge2", "Edge3"], align=True, force_vertical=True)
    doc.recompute()

Draft_PointArray

    import FreeCAD as App
    import Draft

    doc = App.newDocument()

    polygon = Draft.make_polygon(3, radius=500.0)

    p1 = Draft.make_point(App.Vector(1500, 0, 0))
    p2 = Draft.make_point(App.Vector(2500, 0, 0))
    p3 = Draft.make_point(App.Vector(2000, 1000, 0))

    compound = doc.addObject("Part::Compound", "Compound")
    compound.Links = [p1, p2, p3]

    point_array = Draft.make_point_array(polygon, compound)
    doc.recompute()

Draft_Join

    import FreeCAD as App
    import Draft

    doc = App.newDocument()

    p1 = App.Vector(0, 0, 0)
    p2 = App.Vector(500, 0, 0)
    p3 = App.Vector(500, 500, 0)
    p4 = App.Vector(0, 500, 0)

    wire1 = Draft.make_wire([p1, p2])
    wire2 = Draft.make_wire([p2, p3])
    wire3 = Draft.make_wire([p3, p4])
    wire4 = Draft.make_wire([p4, p1])

    Draft.join_wires([wire1, wire3, wire2, wire4])
    doc.recompute()

Draft_Split

    import FreeCAD as App
    import Draft

    doc = App.newDocument()

    p1 = App.Vector(0, 0, 0)
    p2 = App.Vector(500, 0, 0)
    p3 = App.Vector(250, 0, 0)

    wire = Draft.make_wire([p1, p2])

    Draft.split(wire, p3, 1)
    doc.recompute()


Draft_Upgrade


    import FreeCAD as App
    import Draft

    doc = App.newDocument()

    circle = Draft.make_circle(1000)
    rectangle = Draft.make_rectangle(2000, 800)
    doc.recompute()

    add_list1, delete_list1 = Draft.upgrade([circle, rectangle], delete=False)

    line1 = Draft.make_line(App.Vector(2000, 0, 0), App.Vector(2500, 1500, 0))
    line2 = Draft.make_line(App.Vector(2500, 1500, 0), App.Vector(3000, -1000, 0))
    doc.recompute()

    add_list2, delete_list2 = Draft.upgrade([line1, line2], delete=False)

    simple_wire = add_list2[0]
    add_list3, delete_list3 = Draft.upgrade(simple_wire, delete=False)

    closed_wire = add_list3[0]
    add_list4, delete_list4 = Draft.upgrade(closed_wire, delete=False)

    face = add_list4[0]
    add_list5, delete_list5 = Draft.upgrade(face, delete=False)

    doc.recompute()


Draft_Downgrade

    import FreeCAD as App
    import Draft

    doc = App.newDocument()

    circle = Draft.make_circle(1000)
    rectangle = Draft.make_rectangle(2000, 800)
    doc.recompute()

    add_list1, delete_list1 = Draft.upgrade([circle, rectangle], delete=True)

    compound = add_list1[0]
    add_list2, delete_list2 = Draft.downgrade(compound, delete=False)
    face = add_list2[0]
    add_list3, delete_list3 = Draft.downgrade(face, delete=False)

    box = doc.addObject("Part::Box", "Box")
    box.Length = 2300
    box.Width = 800
    box.Height = 1000

    add_list4, delete_list4 = Draft.downgrade(box, delete=True)

    doc.recompute()


Draft_WireToBSpline

    import FreeCAD as App
    import Draft

    doc = App.newDocument()

    p1 = App.Vector(1000, 1000, 0)
    p2 = App.Vector(2000, 1000, 0)
    p3 = App.Vector(2500, -1000, 0)
    p4 = App.Vector(3500, -500, 0)

    base_wire = Draft.make_wire([p1, p2, p3, p4])
    base_spline = Draft.make_bspline([-p1, -1.3*p2, -1.2*p3, -2.1*p4])

    points1 = base_wire.Points
    spline_from_wire = Draft.make_bspline(points1)

    points2 = base_spline.Points
    wire_from_spline = Draft.make_wire(points2)

    doc.recompute()


Draft_Draft2Sketch

    import FreeCAD as App
    import Draft

    doc = App.newDocument()

    rectangle = Draft.make_rectangle(2000, 1000)
    circle = Draft.make_circle(500)
    doc.recompute()

    sketch_from_draft = Draft.make_sketch([rectangle, circle], autoconstraints=True, delete=False, radiusPrecision=0)
    doc.recompute()

    draft_from_sketch = Draft.draftify(sketch_from_draft, delete=False)
    doc.recompute()

Draft_Slope


Draft_FlipDimension

    import FreeCAD as App
    import Draft

    doc = App.newDocument()

    p1 = App.Vector(0, 0, 0)
    p2 = App.Vector(1000, 0, 0)
    p3 = App.Vector(500, 300, 0)
    dimension = Draft.make_dimension(p1, p2, p3)
    dimension.ViewObject.FontSize = 200

    dimension.Normal = dimension.Normal.negative()
    doc.recompute()


Draft_Shape2DView

    import FreeCAD as App
    import Draft

    doc = App.newDocument()

    box = doc.addObject("Part::Box", "Box")
    box.Length = 2300
    box.Width = 500
    box.Height = 1000

    shape1 = Draft.make_shape2dview(box)

    shape2 = Draft.make_shape2dview(box, App.Vector(1, -1, 1))

    shape3 = Draft.make_shape2dview(box, App.Vector(-1, 1, 1), [0, 5])
    shape3.ProjectionMode = "Individual Faces"

    doc.recompute()